autotrade/products/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from autotrade.products.views.views_autotrade import AutotradeCreateCarView, AutotradeVehicleCreateView, \
    AutotradeVehicleView, AutotradeCreateTruckView, AutotradeCreateMotorcycleView, AutotradeCreatePartView, \
    AutotradeEditCarView, AutotradeDetailsCarView, AutotradeUsersProductView, AutotradeDetailsTruckView, \
    AutotradeEditTruckView, AutotradeDetailsMotorcycleView, AutotradeEditMotorcycleView, AutotradeDetailsPartView, \
    AutotradeEditPartView
from autotrade.products.views.views_car import CarCreateView, CarDetailsView, CarEditView, CarDeleteView
from autotrade.products.views.views_motorcycle import MotorcycleCreateView, MotorcycleDeleteView, \
    MotorcycleDetailsView, MotorcycleEditView
from autotrade.products.views.views_part import PartCreateView, PartEditView, PartDetailsView, PartDeleteView
from autotrade.products.views.views_reviews import CarStaffEditView, MotorcycleStaffEditView, TruckStaffEditView, \
    PartStaffEditView
from autotrade.products.views.views_truck import TruckCreateView, TruckDeleteView, TruckDetailsView, TruckEditView
from autotrade.products.views.views_vehicles import UserVehiclesView, UserAdvertisementView

urlpatterns = [
    path('create_car/', CarCreateView.as_view(), name='create car'),
    path('delete_car/<int:pk>/', CarDeleteView.as_view(), name='delete car'),
    path('details_car/<int:pk>/', CarDetailsView.as_view(), name='details car'),
    path('edit_car/<int:pk>/', CarEditView.as_view(), name='edit car'),

    path('create_motorcycle/', MotorcycleCreateView.as_view(), name='create motorcycle'),
    path('delete_motorcycle/<int:pk>/', MotorcycleDeleteView.as_view(), name='delete motorcycle'),
    path('details_motorcycle/<int:pk>/', MotorcycleDetailsView.as_view(), name='details motorcycle'),
    path('edit_motorcycle/<int:pk>/', MotorcycleEditView.as_view(), name='edit motorcycle'),

    path('create_truck/', TruckCreateView.as_view(), name='create truck'),
    path('delete_truck/<int:pk>/', TruckDeleteView.as_view(), name='delete truck'),
    path('details_truck/<int:pk>/', TruckDetailsView.as_view(), name='details truck'),
    path('edit_truck/<int:pk>/', TruckEditView.as_view(), name='edit truck'),

    path('create_part/', PartCreateView.as_view(), name='create part'),
    path('delete_part/<int:pk>/', PartDeleteView.as_view(), name='delete part'),
    path('details_part/<int:pk>/', PartDetailsView.as_view(), name='details part'),
    path('edit_part/<int:pk>/', PartEditView.as_view(), name='edit part'),

    path('user_vehicles/', UserVehiclesView.as_view(), name='user vehicles'),
    path('user_advestisement/', cache_page(60 * 60 * 24 * 365)(UserAdvertisementView.as_view()),
         name='user advertisement'),
    path('autotrade_reviewers_page/', AutotradeUsersProductView.as_view(), name='advertisement to review'),

    path('autotrade_create_car/', AutotradeCreateCarView.as_view(), name='autotrade create car'),
    path('autotrade_details_car/<int:pk>/', AutotradeDetailsCarView.as_view(), name='autotrade details car'),
    path('autotrade_edit_car/<int:pk>/', AutotradeEditCarView.as_view(), name='autotrade edit car'),
    path('autotrade_create_truck/', AutotradeCreateTruckView.as_view(), name='autotrade create truck'),
    path('autotrade_details_truck/<int:pk>/', AutotradeDetailsTruckView.as_view(), name='autotrade details truck'),
    path('autotrade_edit_truck/<int:pk>/', AutotradeEditTruckView.as_view(), name='autotrade edit truck'),
    path('autotrade_create_motorcycle/', AutotradeCreateMotorcycleView.as_view(), name='autotrade create motorcycle'),
    path('autotrade_details_motorcycle/<int:pk>/', AutotradeDetailsMotorcycleView.as_view(),
         name='autotrade details motorcycle'),
    path('autotrade_edit_motorcycle/<int:pk>/', AutotradeEditMotorcycleView.as_view(),
         name='autotrade edit motorcycle'),
    path('autotrade_create_part', AutotradeCreatePartView.as_view(), name='autotrade create part'),
    path('autotrade_details_part/<int:pk>/', AutotradeDetailsPartView.as_view(), name='autotrade details part'),
    path('autotrade_edit_part/<int:pk>/', AutotradeEditPartView.as_view(), name='autotrade edit part'),

    path('autotrade_create_vehicle/', cache_page(60 * 60 * 24 * 365)(AutotradeVehicleCreateView.as_view()),
         name='autotrade create vehicles'),
    path('autotrade_edit_user_car/<int:pk>/', CarStaffEditView.as_view(), name='autotrade user edit car'),
    path('autotrade_edit_user_motorcycle/<int:pk>/', MotorcycleStaffEditView.as_view(),
         name='autotrade user edit motorcycle'),
    path('autotrade_edit_user_truck/<int:pk>/', TruckStaffEditView.as_view(), name='autotrade user edit truck'),
    path('autotrade_edit_user_part/<int:pk>/', PartStaffEditView.as_view(), name='autotrade user edit part'),
    path('autotrade_vehicles/', AutotradeVehicleView.as_view(), name='autotrade vehicles'),
    path('last_viewed_vehicles/', AutotradeVehicleView.as_view(), name='last viewed vehicles'),
]

autotrade/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from autotrade.views import Home, SearchResultView

urlpatterns = [
                  path('admin_admin/', admin.site.urls),
                  path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),

                  path('', Home.as_view(), name='home'),
                  path('search/', SearchResultView.as_view(), name='search bar'),

                  path('', include('autotrade.userapp.urls')),

                  path('', include('autotrade.products.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# import autotrade.signals

autotrade/userapp/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from autotrade.userapp.views import RegisterUser, UserLogin, UserLogout, ProfileDetailsView, ProfileEditView, \
    ProfileUserDeleteView, ChangeUserPasswordView, ProfileCreateView, AutotradeUsersView

urlpatterns = [
    path('register/', RegisterUser.as_view(), name='register'),

    path('change_password/', ChangeUserPasswordView.as_view(), name='change password'),
    path('change_password_done/', TemplateView.as_view(template_name='change_password_done.html'),
         name='change password done'),

    path('password_reset/',
         auth_views.PasswordResetView.as_view(template_name='password_reset.html'),
         name='password_reset'),
    path('password_reset_sent/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_sent.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_form.html'),
         name='password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),
         name='password_reset_complete'),

    path('login/', UserLogin.as_view(), name='login'),
    path('logout/', UserLogout.as_view(), name='logout'),

    path('profile_create/<int:pk>/', ProfileCreateView.as_view(), name='profile create'),
    path('profile_details/<int:pk>/', ProfileDetailsView.as_view(), name='profile details'),
    path('profile_edit/<int:pk>/', ProfileEditView.as_view(), name='profile edit'),
    path('user_profile_delete/<int:pk>/', ProfileUserDeleteView.as_view(), name='profile user delete'),

    path('autotrade_users/', AutotradeUsersView.as_view(), name='users'),
]

autotrade/products/models.py
from django.contrib.auth import get_user_model
from django.core.validators import MinLengthValidator, MinValueValidator, MaxValueValidator
from django.db import models

from cloudinary import models as cloudinary_models

from autotrade.common.helpers import _get_max_choices_length

from autotrade.common.mixins import UsersIsReviewedMixin
from autotrade.products.validators import validate_future_date

UserModel = get_user_model()


class Vehicle(models.Model):
    MAX_MARK_LENGTH = 30
    MIN_MARK_LENGTH = 2

    MAX_MODEL_LENGTH = 30
    MIN_MODEL_LENGTH = 2

    PRICE_DEFAULT_MESSAGE = 'В очакване на цена'
    PRICE_MAX_LENGTH = len(PRICE_DEFAULT_MESSAGE)

    IMAGE_MAXSIZE_IN_MB = 2

    mark = models.CharField(
        max_length=MAX_MARK_LENGTH,
        validators=(
            MinLengthValidator(MIN_MARK_LENGTH),
        ),
        verbose_name='Марка',
    )

    model = models.CharField(
        max_length=MAX_MODEL_LENGTH,
        validators=(
            MinLengthValidator(MIN_MODEL_LENGTH),
        ),
        verbose_name='Модел',
    )

    image = cloudinary_models.CloudinaryField('image')
    # image = models.ImageField(
    #     validators=(
    #         MaxFileSizeInMbValidator(IMAGE_MAXSIZE_IN_MB),
    #     ),
    #     verbose_name='Изберете снимка до 2мб',
    # )

    user = models.ForeignKey(
        UserModel,
        on_delete=models.CASCADE,
    )

    year = models.DateField(
        validators=(
            validate_future_date,
        ),
        verbose_name='Година на производство',
    )

    price = models.CharField(
        max_length=PRICE_MAX_LENGTH,
        default=PRICE_DEFAULT_MESSAGE,
    )

    description = models.TextField(
        null=True,
        blank=True,
        verbose_name='Описание',
    )

    date_of_publication = models.DateField(
        auto_now_add=True,
    )

    class Meta:
        abstract = True

    def __str__(self):
        return f'{self.mark} {self.model} {self.__class__.__name__}'


class CarBase(Vehicle):
    PETROL = 'Дизел'
    GASOLINE = 'Бензин'
    ELECTRICITY = 'Електрически'
    HYBRID = 'Хибрид'
    GAS = 'Газ'
    CHOICES_FUEL = [
        (PETROL, PETROL),
        (GASOLINE, GASOLINE),
        (ELECTRICITY, ELECTRICITY),
        (HYBRID, HYBRID),
        (GAS, GAS),
    ]
    MAX_CHOICES_FUEL_LENGTH = _get_max_choices_length(CHOICES_FUEL)

    MOTOR_MIN_CAPACITY = 800
    MOTOR_MAX_CAPACITY = 7000

    fuel = models.CharField(
        max_length=MAX_CHOICES_FUEL_LENGTH,
        choices=CHOICES_FUEL,
        verbose_name='Гориво',
    )

    motor = models.PositiveIntegerField(
        validators=(
            MaxValueValidator(MOTOR_MAX_CAPACITY),
            MinValueValidator(MOTOR_MIN_CAPACITY),
        ),
        verbose_name='Обем на двигател',
    )

    class Meta:
        abstract = True


class MotorcycleBase(Vehicle):
    AIR_COOLING = 'Въздушно'
    WATER_COOLING = 'Водно'
    CHOICES_COOLING = [
        (AIR_COOLING, AIR_COOLING),
        (WATER_COOLING, WATER_COOLING),
    ]
    COOLING_MAX_LENGTH = _get_max_choices_length(CHOICES_COOLING)

    CROSS = 'Кросов'
    SPORTS = 'Пистов'
    CHOPPER = 'Чопър'
    CHOICE_TYPE = [
        (CROSS, CROSS),
        (SPORTS, SPORTS),
        (CHOPPER, CHOPPER),
    ]
    TYPE_MAX_LENGTH = _get_max_choices_length(CHOICE_TYPE)

    motor_type = models.CharField(
        max_length=TYPE_MAX_LENGTH,
        choices=CHOICE_TYPE,
        null=True,
        blank=True,
        verbose_name='Тип на мотора (незадължително поле)'
    )

    cooling = models.CharField(
        max_length=COOLING_MAX_LENGTH,
        choices=CHOICES_COOLING,
        null=True,
        blank=True,
        verbose_name='Вид охлаждане (незадължително поле)'
    )

    class Meta:
        abstract = True


class TruckBase(Vehicle):
    MIN_TOTAL_WEIGHT = 0

    MIN_CAPACITY = 0

    VAN = 'Ван'
    SPECIAL = 'Специален'
    CONSTRUCTION = 'Строителна техника'
    CATEGORY_CHOICES = [
        (VAN, VAN),
        (SPECIAL, SPECIAL),
        (CONSTRUCTION, CONSTRUCTION),
    ]
    MAX_CATEGORY_LENGTH = _get_max_choices_length(CATEGORY_CHOICES)

    total_weight = models.FloatField(
        validators=(
            MinValueValidator(MIN_TOTAL_WEIGHT),
        ),
        verbose_name='Общо тегло'
    )

    capacity = models.FloatField(
        validators=(
            MinValueValidator(MIN_TOTAL_WEIGHT),
        ),
        verbose_name='Товароносимост'
    )

    category = models.CharField(
        max_length=MAX_CATEGORY_LENGTH,
        choices=CATEGORY_CHOICES,
        null=True,
        blank=True,
        verbose_name='Категория'
    )

    class Meta:
        abstract = True


class PartBase(models.Model):
    MOTOR = 'Двигател'
    TRANSMISSION = 'Скорости'
    COUPE = 'КУПЕ'
    OTHERS = 'Други'
    PARTS_CHOICES = [
        (MOTOR, MOTOR),
        (TRANSMISSION, TRANSMISSION),
        (COUPE, COUPE),
        (OTHERS, OTHERS),
    ]
    MAX_PARTS_LENGTH = _get_max_choices_length(PARTS_CHOICES)

    NEW = 'Ново'
    USED = 'Използвано'
    UNPACKED = 'Разопаковано'
    CONDITION_CHOISES = [
        (NEW, NEW),
        (USED, USED),
        (UNPACKED, UNPACKED),
    ]
    MAX_CONDITION_LENGTH = _get_max_choices_length(CONDITION_CHOISES)

    MAX_CATALOG_CODE_LENGTH = 25

    MAX_NAME_LENGTH = 33

    PRICE_DEFAULT_MESSAGE = 'В очакване на цена'
    PRICE_MAX_LENGTH = len(PRICE_DEFAULT_MESSAGE)

    IMAGE_MAXSIZE_IN_MB = 1

    name = models.CharField(
        max_length=MAX_NAME_LENGTH,
        verbose_name='Наименование',
    )
    parts_category = models.CharField(
        max_length=MAX_PARTS_LENGTH,
        choices=PARTS_CHOICES,
        verbose_name="Категория"
    )

    condition = models.CharField(
        max_length=MAX_CONDITION_LENGTH,
        choices=CONDITION_CHOISES,
        verbose_name='Състояние',
    )

    catalog_number = models.CharField(
        max_length=MAX_CATALOG_CODE_LENGTH,
        null=True,
        blank=True,
        verbose_name='Каталожен номер'
    )

    price = models.CharField(
        max_length=PRICE_MAX_LENGTH,
        default=PRICE_DEFAULT_MESSAGE,
        verbose_name='Цена',
    )

    image = cloudinary_models.CloudinaryField('image')
    # image = models.ImageField(
    #     validators=(
    #         MaxFileSizeInMbValidator(IMAGE_MAXSIZE_IN_MB),
    #     ),
    #     verbose_name='Изберете снимка до 1мб',
    # )

    description = models.TextField(
        null=True,
        blank=True,
        verbose_name='Описание',
    )

    user = models.ForeignKey(
        UserModel,
        on_delete=models.CASCADE,
    )

    date_of_publication = models.DateField(
        auto_now_add=True,
    )

    class Meta:
        abstract = True

    def __str__(self):
        return f'{self.name}'


class Car(CarBase, UsersIsReviewedMixin):
    is_reviewed = UsersIsReviewedMixin.is_reviewed


class Motorcycle(MotorcycleBase, UsersIsReviewedMixin):
    is_reviewed = UsersIsReviewedMixin.is_reviewed


class Truck(TruckBase, UsersIsReviewedMixin):
    is_reviewed = UsersIsReviewedMixin.is_reviewed


class Part(PartBase, UsersIsReviewedMixin):
    is_reviewed = UsersIsReviewedMixin.is_reviewed


class AutotradeMotorcycle(MotorcycleBase):
    pass


class AutotradeCar(CarBase):
    pass


class AutotradeTruck(TruckBase):
    pass


class AutotradePart(PartBase):
    pass

autotrade/products/views/views_car.py
from cloudinary import uploader
from django.contrib.auth import mixins
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import generic

from autotrade.common.mixins import CurrentUserSaveProductMixin, OwnerAndPermStaffHaveCRUDPermissionMixin, \
    DeleteOnlyOwnersVehiclesAndDestroyImageMixin, OwnerCanNotEditReviewedProductsMixin, GetSuccessUrlAfterDeleteMixin
from autotrade.products.forms import CarCreateForm, CarEditForm
from autotrade.products.models import Car


class CarCreateView(CurrentUserSaveProductMixin, mixins.LoginRequiredMixin, generic.CreateView):
    template_name = 'cars/create_car.html'
    model = Car
    form_class = CarCreateForm
    success_url = reverse_lazy('user vehicles')


class CarDetailsView(OwnerAndPermStaffHaveCRUDPermissionMixin, mixins.LoginRequiredMixin, generic.DetailView):
    model = Car
    template_name = 'cars/details_car.html'


class CarDeleteView(GetSuccessUrlAfterDeleteMixin, DeleteOnlyOwnersVehiclesAndDestroyImageMixin,
                    mixins.LoginRequiredMixin, generic.DeleteView):
    template_name = 'cars/delete_car.html'
    model = Car


class CarEditView(OwnerCanNotEditReviewedProductsMixin,
                  OwnerAndPermStaffHaveCRUDPermissionMixin,
                  mixins.LoginRequiredMixin, generic.UpdateView):
    template_name = 'cars/edit_car.html'
    model = Car
    form_class = CarEditForm

    def get_success_url(self):
        return reverse_lazy('details car', kwargs={'pk': self.object.pk})

autotrade/views.py
from django.db.models import Q
from django.views import generic

from autotrade.products.models import AutotradeCar, AutotradeTruck, AutotradeMotorcycle, AutotradePart


class Home(generic.TemplateView):
    template_name = 'index.html'


class SearchResultView(generic.ListView):
    model = AutotradeCar
    template_name = 'search.html'

    def get_queryset(self):
        query = self.request.GET.get("q")

        cars = list(AutotradeCar.objects.filter(Q(mark__icontains=query) or Q(model__icontains=query)))
        trucks = list(AutotradeTruck.objects.filter(Q(mark__icontains=query) or Q(model__icontains=query)))
        motorcycles = list(AutotradeMotorcycle.objects.filter(Q(mark__icontains=query) or Q(model__icontains=query)))
        parts = list(AutotradePart.objects.filter(Q(name__icontains=query)))
        object_list = cars + trucks + motorcycles + parts

        return object_list

autotrade/products/templates/autotrade/autotrade_create_car.html
{% extends 'base/base.html' %}
{% block content %}
    <form method="post" action="{% url 'autotrade create car' %}" enctype="multipart/form-data">
        {{ form }}
        {% csrf_token %}
        <button>Запази</button>
    </form>
{% endblock %}

autotrade/products/templates/autotrade/autotrade_create_motorcycle.html
{% extends 'base/base.html' %}
{% block content %}
    <form method="post" action="{% url 'autotrade create motorcycle' %}" enctype="multipart/form-data">
        {{ form }}
        {% csrf_token %}
        <button>Запази</button>
    </form>
{% endblock %}

autotrade/products/templates/autotrade/autotrade_create_motorcycles.html
{% extends 'base/base.html' %}
{% block content %}
    <form method="post" action="{% url 'autotrade create motorcycles' %}" enctype="multipart/form-data">
        {{ form }}
        {% csrf_token %}
        <button>Запази</button>
    </form>
{% endblock %}

autotrade/products/templates/autotrade/autotrade_create_part.html
{% extends 'base/base.html' %}
{% block content %}
    <form method="post" action="{% url 'autotrade create part' %}" enctype="multipart/form-data">
        {{ form }}
        {% csrf_token %}
        <button>Запази</button>
    </form>
{% endblock %}

autotrade/products/templates/autotrade/autotrade_create_parts.html
{% extends 'base/base.html' %}
{% block content %}
    <form method="post" action="{% url 'autotrade create parts' %}" enctype="multipart/form-data">
        {{ form }}
        {% csrf_token %}
        <button>Запази</button>
    </form>
{% endblock %}

autotrade/products/templates/autotrade/autotrade_create_truck.html
{% extends 'base/base.html' %}
{% block content %}
    <form method="post" action="{% url 'autotrade create truck' %}" enctype="multipart/form-data">
        {{ form }}
        {% csrf_token %}
        <button>Запази</button>
    </form>
{% endblock %}

autotrade/products/templates/autotrade/autotrade_create_vehicles.html
{% extends 'base/base.html' %}
{% load cache %}
{% load static %}
{% block content %}
    <center>
        <table>
            <tr>
                <td><a href="{% url 'autotrade create car' %}"><img src="{% static 'images/car.jpg' %}"
                                                                    alt="Лeки автомобили" style="width:600px;height:200px;"></a>
                </td>
                <td><a href="{% url 'autotrade create motorcycle' %}"><img src="{% static 'images/motorcycle.jpg' %}"
                                                                           alt="Мотоциклети"
                                                                           style="width:300px;height:400px;"></a>
                </td>
            </tr>
            <tr>
                <td><a href="{% url 'autotrade create car' %}">Леки автомобили</a></td>
                <td><a href="{% url 'autotrade create motorcycle' %}">Мотоциклети</a></td>
            </tr>
            <tr>
                <td><a href="{% url 'autotrade create truck' %}"><img src="{% static 'images/truck.jpg' %}"
                                                                      alt="Товарни автомобили"
                                                                      style="width:600px;height:330px;"></a>
                </td>
                <td><a href="{% url 'autotrade create part' %}"><img src="{% static 'images/part.jpg' %}"
                                                                     alt="Части" style="width:600px;height:330px;"></a>
                </td>
            </tr>
            <tr>
                <td><a href="{% url 'autotrade create truck' %}">Товарни автомобили</a></td>
                <td><a href="{% url 'autotrade create part' %}">Части</a></td>
            </tr>
        </table>
    </center>
{% endblock %}

autotrade/products/templates/autotrade/autotrade_details_car.html
{% extends 'base/base.html' %}
{% block content %}
    <img src="{{ object.image.url }}" alt="{{ object.mark }}" width="300" height="300">
    <h5><u>Марка:</u> {{ object.mark }}</h5>
    <h5><u>Модел:</u> {{ object.model }}</h5>
    <h5><u>Гориво:</u> {{ object.fuel }}</h5>
    <h5><u>Година:</u> {{ object.year }}</h5>
    <h5><u>Двигател:</u> {{ object.motor }}</h5>
    <h5><u>Описание:</u> <strong>{{ object.description }}</strong></h5>
    <h5><u>Цена:</u> <strong>{{ object.price }}</strong></h5>
    <a href="{% url 'autotrade vehicles' %}"><button>Назад към всички обяви</button></a>
    <a href="{% url 'autotrade edit car' object.pk %}"><button>Редакция</button></a>
{% endblock %}

autotrade/products/templates/autotrade/autotrade_details_motorcycle.html
{% extends 'base/base.html' %}
{% block content %}
    <img src="{{ object.image.url }}" alt="{{ object.mark }}" width="300" height="300">
    <h5><u>Марка:</u> {{ object.mark }}</h5>
    <h5><u>Модел:</u> {{ object.model }}</h5>
    <h5><u>Година:</u> {{ object.year }}</h5>
    {% if object.motor_type %}
        <h5><u>Тип:</u> {{ object.motor_type }}</h5>
    {% endif %}
    {% if object.cooling %}
        <h5><u>Охлаждане:</u> {{ object.cooling }}</h5>
    {% endif %}
    {% if object.description %}
        <h5><u>Описание:</u> <strong>{{ object.description }}</strong></h5>
    {% endif %}
    <h5><u>Цена:</u> <strong>{{ object.price }}</strong></h5>
    {# Номерът на конкретния служител качил обява #}
    <h5><u>Телефон за контакт:</u> <strong>{{ object.user.phone_number }}</strong></h5>
    <a href="{% url 'autotrade vehicles' %}">
        <button>Назад към всички обяви</button>
    </a>
    {% if perms.products.change_autotrademotorcycle %}
        <a href="{% url 'autotrade edit motorcycle' object.pk %}">
            <button>Редакция</button>
        </a>
    {% endif %}
{% endblock %}

autotrade/products/templates/autotrade/autotrade_details_part.html
{% extends 'base/base.html' %}
{% block content %}
    <img src="{{ object.image.url }}" alt="{{ object.mark }}" width="300" height="300">
    <h5><u>Наименование:</u> {{ object.mark }}</h5>
    <h5><u>Категория:</u> {{ object.category }}</h5>
    <h5><u>Състояние:</u> {{ object.condition }}</h5>
    {% if object.catalog_number %}
        <h5><u>Каталожен номер:</u> {{ object.total_weight }}</h5>
    {% endif %}
    <h5><u>Товароносимост:</u> {{ object.total_weight }}</h5>
    {% if object.description %}
        <h5><u>Описание:</u> <strong>{{ object.description }}</strong></h5>
    {% endif %}
    <h5><u>Цена:</u> <strong>{{ object.price }}</strong></h5>
    {# Номерът на конкретния служител качил обява #}
    <h5><u>Телефон за контакт:</u> <strong>{{ object.user.phone_number }}</strong></h5>
    <a href="{% url 'autotrade vehicles' %}">
        <button>Назад към всички обяви</button>
    </a>
    {% if perms.products.change_autotradepart %}
        <a href="{% url 'autotrade edit part' object.pk %}">
            <button>Редакция</button>
        </a>
    {% endif %}
{% endblock %}

autotrade/products/templates/autotrade/autotrade_edit_car.html
{% extends 'base/base.html' %}
{% block content %}
    <form method="post" action="{% url 'autotrade edit car' object.pk %}" enctype="multipart/form-data">
        {{ form }}
        {% csrf_token %}
        <button>Промени</button>
    </form>
        <a href="{% url 'autotrade vehicles' %}"><button>Назад към обяви</button></a>
{% endblock %}

autotrade/products/templates/autotrade/autotrade_edit_truck.html
{% extends 'base/base.html' %}
{% block content %}
    <form method="post" action="{% url 'autotrade edit truck' object.pk %}" enctype="multipart/form-data">
        {{ form }}
        {% csrf_token %}
        <button>Промени</button>
    </form>
        <a href="{% url 'autotrade vehicles' %}"><button>Назад към обяви</button></a>
{% endblock %}